### ISSUE TITLE
Crash on Lion after indexing

### ISSUE THREAD

**Issue by gf3** [atg/Ingredients#31] opened 2011-08-22 20:50 UTC
Ingredients first launched properly, and began to index the docs. When it was done indexing, the app crashed. Now the app crashes immediately on launch.

Here's the info from the crash reporter: https://gist.github.com/6a2573ed09436fab70b1

**Comment by timeimp** [comment] 2011-08-25 12:20
I'll +1 on this issue. Indexed fine. Went to search for something. Ingredients died. Same error as above. (Lion 10.7.1)

**Comment by bjtitus** [comment] 2011-08-26 15:53
Same issue here. Same backtrace on the crashed thread with a problem in sqlite3Api.

**Comment by vytis** [comment] 2011-08-31 07:36
I also get this crash. Unfortunately the app is unusable on 10.7.1 :/

**Comment by hujunfeng** [comment] 2011-09-03 08:58
Same here. Crash on 10.7.1.

**Comment by dannolan** [comment] 2011-09-07 02:02
Crashes on 10.7.1 on my machine as well.

**Comment by hunterhacker** [comment] 2011-09-12 03:36
Same issue here on Lion 10.7.1 with XCode 4.2 Build 4D177b.

**Comment by pypt** [comment] 2011-10-05 19:33
I'd guess it has something to do with Core Data not being happy with running in a separate thread, encountering random freed pointers, etc.

I've tried changing `- (dispatch_queue_t)backgroundQueue` method in `IGKApplicationDelegate.mm` in a way so that the "background" processes of the app run on the same (main) thread:

```
- (dispatch_queue_t)backgroundQueue
{
    if (backgroundQueue == NULL) {
        //backgroundQueue = dispatch_queue_create(NULL, NULL);
        backgroundQueue = dispatch_get_main_queue();
    }

    return backgroundQueue;
}
```

Now it appears to work fine on Lion (unless I didn't provoke it enough to crash), just that the interface became sluggish as the UI has to wait for Core Data to fetch search results. Anyway, not that bad as a temporary solution.

**Comment by dannolan** [comment] 2011-10-06 00:13
Fork, patch it and submit a pull request, I'd say

**Comment by pypt** [comment] 2011-10-06 06:33
As this would be a "better than nothing" fix, I don't see how that would get pushed to master.

**Comment by fossil12** [comment] 2011-10-10 09:45
+1 same here with lion 10.7.1

**Comment by anddam** [comment] 2012-01-19 20:26
Isn't this issue a duplicate of #16?

**Comment by pypt** [comment] 2012-01-21 01:09
Issue #16 looks very similar, yes.

**Closed as completed** 2015-06-01 18:19 UTC
